services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portofolio-dani
    restart: unless-stopped
    ports:
      - '3005:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: ['npm', 'run', 'start']
