services:
  app:
    image: portofolio-app-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: ${DOCKER_CONTAINER_NAME_PROD:-portofolio-dani}
    restart: ${DOCKER_RESTART_POLICY:-unless-stopped}
    ports:
      - '${DOCKER_APP_PORT_PROD:-3005}:${APP_INTERNAL_PORT:-3000}'
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=${NEXT_TELEMETRY_DISABLED:-1}
    command:
      ['npm', 'run', 'start', '--', '--hostname', '0.0.0.0', '--port', '${APP_INTERNAL_PORT:-3000}']
